### ISSUE TITLE
TypeError: Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/CCJam-2016#4]
```
[Sun Jul 03 2016 02:49:13] [ERROR] TypeError: Cannot read property 'count' of undefined
    at EntityDwarf.interact (/var/jamrogue/dist/entities/entity_mob.js:251:32)
    at /var/jamrogue/dist/routes/entity_interact.js:51:10
    at Layer.handle [as handle_request] (/var/jamrogue/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/jamrogue/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/jamrogue/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/jamrogue/node_modules/express/lib/router/layer.js:95:5)
    at /var/jamrogue/node_modules/express/lib/router/index.js:277:22
    at param (/var/jamrogue/node_modules/express/lib/router/index.js:349:14)
    at param (/var/jamrogue/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/var/jamrogue/node_modules/express/lib/router/index.js:410:3)
    at next (/var/jamrogue/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/var/jamrogue/node_modules/body-parser/lib/types/json.js:94:7)
    at Layer.handle [as handle_request] (/var/jamrogue/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/jamrogue/node_modules/express/lib/router/index.js:312:13)
    at /var/jamrogue/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/jamrogue/node_modules/express/lib/router/index.js:330:12)
    at next (/var/jamrogue/node_modules/express/lib/router/index.js:271:10)
    at /var/jamrogue/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/var/jamrogue/node_modules/raw-body/index.js:262:16)
    at done (/var/jamrogue/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/var/jamrogue/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
```

Occurs when you interact with a mob without an equipped item

**Comment by CrazedProgrammer** [comment]
Fixed in https://github.com/Lemmmy/jamROGUE/commit/c640af54b1f8c27e63b48b0e7b25efa8f9fbc7ff
